### ISSUE TITLE
Can't use clean_svg.py: RuntimeError

### ISSUE THREAD

**Issue by 04ELY** [linuxwacom/libwacom#531]
I wanted to make an MR for Deco 01 (and v2) but when I try to clean the SVG, it returns error, can you help?
Here's the SVG
![xp-pen-deco-01](https://user-images.githubusercontent.com/60751519/201002172-9f2ea333-0900-47ae-a173-4540f50f4273.svg)

Error:
```
Traceback (most recent call last):
  File "/home/ely/Projects/Linux/input/libwacom/tools/clean_svg.py", line 323, in <module>
    clean_svg(root, args.tabletname[0])
  File "/home/ely/Projects/Linux/input/libwacom/tools/clean_svg.py", line 299, in clean_svg
    traverse_and_clean(root)
  File "/home/ely/Projects/Linux/input/libwacom/tools/clean_svg.py", line 41, in traverse_and_clean
    for key in node.attrib.keys():
RuntimeError: dictionary changed size during iteration
```
Python: `Python 3.11.0 (main, Oct 24 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] on linux`

**Comment by whot** [comment]
huh, indeed, I wonder how this ever worked... thanks for finding this, I think #532 should fix it.
